// Code generated by mockery v2.28.1. DO NOT EDIT.

package float

import (
	acal "github.com/jamestrandung/go-accountable-calculation/acal"
	boolean "github.com/jamestrandung/go-accountable-calculation/boolean"

	decimal "github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"
)

// MockValue is an autogenerated mock type for the Value type
type MockValue struct {
	mock.Mock
}

// Abs provides a mock function with given fields:
func (_m *MockValue) Abs() Simple {
	ret := _m.Called()

	var r0 Simple
	if rf, ok := ret.Get(0).(func() Simple); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(Simple)
	}

	return r0
}

// Add provides a mock function with given fields: _a0
func (_m *MockValue) Add(_a0 acal.TypedValue[decimal.Decimal]) Simple {
	ret := _m.Called(_a0)

	var r0 Simple
	if rf, ok := ret.Get(0).(func(acal.TypedValue[decimal.Decimal]) Simple); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(Simple)
	}

	return r0
}

// Ceil provides a mock function with given fields:
func (_m *MockValue) Ceil() Simple {
	ret := _m.Called()

	var r0 Simple
	if rf, ok := ret.Get(0).(func() Simple); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(Simple)
	}

	return r0
}

// Decimal provides a mock function with given fields:
func (_m *MockValue) Decimal() decimal.Decimal {
	ret := _m.Called()

	var r0 decimal.Decimal
	if rf, ok := ret.Get(0).(func() decimal.Decimal); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	return r0
}

// Div provides a mock function with given fields: _a0
func (_m *MockValue) Div(_a0 acal.TypedValue[decimal.Decimal]) Simple {
	ret := _m.Called(_a0)

	var r0 Simple
	if rf, ok := ret.Get(0).(func(acal.TypedValue[decimal.Decimal]) Simple); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(Simple)
	}

	return r0
}

// Equals provides a mock function with given fields: _a0
func (_m *MockValue) Equals(_a0 acal.TypedValue[decimal.Decimal]) boolean.Simple {
	ret := _m.Called(_a0)

	var r0 boolean.Simple
	if rf, ok := ret.Get(0).(func(acal.TypedValue[decimal.Decimal]) boolean.Simple); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(boolean.Simple)
	}

	return r0
}

// ExtractValues provides a mock function with given fields: cache
func (_m *MockValue) ExtractValues(cache acal.IValueCache) acal.IValueCache {
	ret := _m.Called(cache)

	var r0 acal.IValueCache
	if rf, ok := ret.Get(0).(func(acal.IValueCache) acal.IValueCache); ok {
		r0 = rf(cache)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(acal.IValueCache)
		}
	}

	return r0
}

// Float provides a mock function with given fields:
func (_m *MockValue) Float() float64 {
	ret := _m.Called()

	var r0 float64
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// Floor provides a mock function with given fields:
func (_m *MockValue) Floor() Simple {
	ret := _m.Called()

	var r0 Simple
	if rf, ok := ret.Get(0).(func() Simple); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(Simple)
	}

	return r0
}

// GetAlias provides a mock function with given fields:
func (_m *MockValue) GetAlias() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetName provides a mock function with given fields:
func (_m *MockValue) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetTypedValue provides a mock function with given fields:
func (_m *MockValue) GetTypedValue() decimal.Decimal {
	ret := _m.Called()

	var r0 decimal.Decimal
	if rf, ok := ret.Get(0).(func() decimal.Decimal); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	return r0
}

// GetValue provides a mock function with given fields:
func (_m *MockValue) GetValue() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// HasIdentity provides a mock function with given fields:
func (_m *MockValue) HasIdentity() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Identify provides a mock function with given fields:
func (_m *MockValue) Identify() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Inv provides a mock function with given fields:
func (_m *MockValue) Inv() Simple {
	ret := _m.Called()

	var r0 Simple
	if rf, ok := ret.Get(0).(func() Simple); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(Simple)
	}

	return r0
}

// IsNegative provides a mock function with given fields:
func (_m *MockValue) IsNegative() boolean.Simple {
	ret := _m.Called()

	var r0 boolean.Simple
	if rf, ok := ret.Get(0).(func() boolean.Simple); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(boolean.Simple)
	}

	return r0
}

// IsNil provides a mock function with given fields:
func (_m *MockValue) IsNil() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsPositive provides a mock function with given fields:
func (_m *MockValue) IsPositive() boolean.Simple {
	ret := _m.Called()

	var r0 boolean.Simple
	if rf, ok := ret.Get(0).(func() boolean.Simple); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(boolean.Simple)
	}

	return r0
}

// IsZero provides a mock function with given fields:
func (_m *MockValue) IsZero() boolean.Simple {
	ret := _m.Called()

	var r0 boolean.Simple
	if rf, ok := ret.Get(0).(func() boolean.Simple); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(boolean.Simple)
	}

	return r0
}

// LargerThan provides a mock function with given fields: _a0
func (_m *MockValue) LargerThan(_a0 acal.TypedValue[decimal.Decimal]) boolean.Simple {
	ret := _m.Called(_a0)

	var r0 boolean.Simple
	if rf, ok := ret.Get(0).(func(acal.TypedValue[decimal.Decimal]) boolean.Simple); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(boolean.Simple)
	}

	return r0
}

// LargerThanEquals provides a mock function with given fields: _a0
func (_m *MockValue) LargerThanEquals(_a0 acal.TypedValue[decimal.Decimal]) boolean.Simple {
	ret := _m.Called(_a0)

	var r0 boolean.Simple
	if rf, ok := ret.Get(0).(func(acal.TypedValue[decimal.Decimal]) boolean.Simple); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(boolean.Simple)
	}

	return r0
}

// Mul provides a mock function with given fields: _a0
func (_m *MockValue) Mul(_a0 acal.TypedValue[decimal.Decimal]) Simple {
	ret := _m.Called(_a0)

	var r0 Simple
	if rf, ok := ret.Get(0).(func(acal.TypedValue[decimal.Decimal]) Simple); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(Simple)
	}

	return r0
}

// Neg provides a mock function with given fields:
func (_m *MockValue) Neg() Simple {
	ret := _m.Called()

	var r0 Simple
	if rf, ok := ret.Get(0).(func() Simple); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(Simple)
	}

	return r0
}

// NotEquals provides a mock function with given fields: _a0
func (_m *MockValue) NotEquals(_a0 acal.TypedValue[decimal.Decimal]) boolean.Simple {
	ret := _m.Called(_a0)

	var r0 boolean.Simple
	if rf, ok := ret.Get(0).(func(acal.TypedValue[decimal.Decimal]) boolean.Simple); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(boolean.Simple)
	}

	return r0
}

// Round provides a mock function with given fields: decimalPlace
func (_m *MockValue) Round(decimalPlace acal.TypedValue[decimal.Decimal]) Simple {
	ret := _m.Called(decimalPlace)

	var r0 Simple
	if rf, ok := ret.Get(0).(func(acal.TypedValue[decimal.Decimal]) Simple); ok {
		r0 = rf(decimalPlace)
	} else {
		r0 = ret.Get(0).(Simple)
	}

	return r0
}

// SetAlias provides a mock function with given fields: _a0
func (_m *MockValue) SetAlias(_a0 string) {
	_m.Called(_a0)
}

// SmallerThan provides a mock function with given fields: _a0
func (_m *MockValue) SmallerThan(_a0 acal.TypedValue[decimal.Decimal]) boolean.Simple {
	ret := _m.Called(_a0)

	var r0 boolean.Simple
	if rf, ok := ret.Get(0).(func(acal.TypedValue[decimal.Decimal]) boolean.Simple); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(boolean.Simple)
	}

	return r0
}

// SmallerThanEquals provides a mock function with given fields: _a0
func (_m *MockValue) SmallerThanEquals(_a0 acal.TypedValue[decimal.Decimal]) boolean.Simple {
	ret := _m.Called(_a0)

	var r0 boolean.Simple
	if rf, ok := ret.Get(0).(func(acal.TypedValue[decimal.Decimal]) boolean.Simple); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(boolean.Simple)
	}

	return r0
}

// Stringify provides a mock function with given fields:
func (_m *MockValue) Stringify() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Sub provides a mock function with given fields: _a0
func (_m *MockValue) Sub(_a0 acal.TypedValue[decimal.Decimal]) Simple {
	ret := _m.Called(_a0)

	var r0 Simple
	if rf, ok := ret.Get(0).(func(acal.TypedValue[decimal.Decimal]) Simple); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(Simple)
	}

	return r0
}

// ToSyntaxOperand provides a mock function with given fields: nextOp
func (_m *MockValue) ToSyntaxOperand(nextOp acal.Op) *acal.SyntaxOperand {
	ret := _m.Called(nextOp)

	var r0 *acal.SyntaxOperand
	if rf, ok := ret.Get(0).(func(acal.Op) *acal.SyntaxOperand); ok {
		r0 = rf(nextOp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*acal.SyntaxOperand)
		}
	}

	return r0
}

type mockConstructorTestingTNewMockValue interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockValue creates a new instance of MockValue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockValue(t mockConstructorTestingTNewMockValue) *MockValue {
	mock := &MockValue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
