// Code generated by mockery v2.28.1. DO NOT EDIT.

package acal

import mock "github.com/stretchr/testify/mock"

// mockSourcer is an autogenerated mock type for the sourcer type
type mockSourcer struct {
	mock.Mock
}

// From provides a mock function with given fields: _a0
func (_m *mockSourcer) From(_a0 Source) {
	_m.Called(_a0)
}

// GetSource provides a mock function with given fields:
func (_m *mockSourcer) GetSource() Source {
	ret := _m.Called()

	var r0 Source
	if rf, ok := ret.Get(0).(func() Source); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(Source)
	}

	return r0
}

type mockConstructorTestingTnewMockSourcer interface {
	mock.TestingT
	Cleanup(func())
}

// newMockSourcer creates a new instance of mockSourcer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockSourcer(t mockConstructorTestingTnewMockSourcer) *mockSourcer {
	mock := &mockSourcer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
